# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: c36e468794f9256d5e922c399240d49782ba04f1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 3ab3ad47c7ef2e5550274fe7da57e1b5e2dd278e
    hooks:
      - id: isort
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry
